export const AppLogo = require('./AppLogo.png');
export const OneWayIcon = require('./OneWayIcon.png');
export const LeftArrow = require('./arrow-left-tatd.png');
export const OpenEnvelop = require('./open_envlop.png');
export const Address = require('./address.png');
export const CallingGif = require('./calling.gif');
export const RightArrow = require('./arrow-right-tatd.png');
export const ArrowFadeBlue = require('./arrow_fade_blue.png')
export const Wallet_Icon = require( './wallet_icon.png')
export const Check_Offer = require('./check_offer.png')
export const RightArrow_White = require("./arrow-right-white-tatd.png")
export const WhatsApp_Icon = require('./whatsapp.png')
export const Facebook_Icon = require('./facebook.png')
export const Twitter_Icon = require('./twitter.png')
export const Linkedin_Icon = require('./linkedin.png')
export const Copy_Icon = require('./copy.png')
export const CloseEnvelop = require('./closed_envlop.png')
export const bluelogo = require('./bluelogo.png')
export const whitelogo = require('./logo-white.png')
export const Headerlogo = require('./headerLogo.png')
export const googleLogo = require('./google.png')
export const Mask = require('./mask.png')
export const Triangle_Icon = require('./rt_icon.png')

